version: '3.0'

expectations:
  population_size: 5000

actions:

  gen_dataset_table:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/data/dataset_table.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv.gz

  prep_descrip_r:
    run: r:analysis/data_prep_descrip.R
    needs: [gen_dataset_table]
    outputs:
      highly_sensitive:
        data: output/data/data_input.csv

  prep_descrip_stata:
   run: stata-mp:analysis/data_prep_descrip.do
   needs: [gen_dataset_table]
   outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data: output/main.dta






