version: '3.0'

# Ignore this`expectation` block. It is required but not used, and will be removed in future versions.
expectations:
  population_size: 5000

actions:
  # generate_dataset:
  #   run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
  #   outputs:
  #     highly_sensitive:
  #       dataset: output/dataset.csv.gz

  gen_dataset_table:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/data/dataset_table.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv.gz

  prep_descrip:
   run: stata-mp:analysis/data_prep_descrip.do
   needs: [gen_dataset_table]
   outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data1: output/main.dta
        data2: output/sensitivity.dta


