version: '3.0'

expectations:
  population_size: 5000

actions:

  gen_dataset_table:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/data/dataset_table.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv.gz

  prep_descrip_r:
    run: r:latest analysis/data_prep_descrip.r
    needs: [gen_dataset_table]
    outputs:
      moderately_sensitive:
        table1: output/tables/table1_sum.csv
        table2: output/tables/table1_redacted_under8.csv
      highly_sensitive:
        data1: output/data/data4analyses.csv
        data2: output/data/high_risk_cohort.csv
        data3: output/data/high_risk_ever_cohort.csv
        data4: output/data/high_risk_cohort_inc60ddeath.csv

  prep_model_surv_r:
    run: r:latest analysis/prep_model_surv.r
    needs: [prep_descrip_r]
    outputs: 
      moderately_sensitive:
        table3: output/tables/table_cox_model_6m.csv
      highly_sensitive:
        data5: output/data/high_risk_surv_data.csv

  prep_model_1surv_r:
    run: r:latest analysis/prep_model_1surv.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data6: output/data/high_risk_surv_data1.csv
  
  prep_model_2surv_r:
    run: r:latest analysis/prep_model_2surv.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data7: output/data/high_risk_surv_data2.csv

  prep_descrip_agegp_r:
    run: r:latest analysis/data_prep_descrip_1agegp.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data8: output/data/high_risk_vars_age_rc.csv
      moderately_sensitive:
        table01: output/tables/high_risk_vars_age_rc_table.csv

  prep_model_surv_sen_r:
    run: r:latest analysis/prep_model_surv_sen.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data9: output/data/high_risk_surv_data0.csv

  prep_model_1surv_sen_r:
    run: r:latest analysis/prep_model_1surv_sen.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data10: output/data/high_risk_surv_data01.csv

  prep_model_2surv_sen_r:
    run: r:latest analysis/prep_model_2surv_sen.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data11: output/data/high_risk_surv_data02.csv





