version: '3.0'

expectations:
  population_size: 5000

actions:

  gen_dataset_table:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/data/dataset_table.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv.gz

  prep_descrip_r:
    run: r:latest analysis/data_prep_descrip.r
    needs: [gen_dataset_table]
    outputs:
      moderately_sensitive:
        data1: output/tables/table1_ab.csv
        data2: output/tables/table1a_redacted_8b.csv
        data3: output/tables/table1b_redacted_8b.csv
      highly_sensitive:
        data4: output/data/data4analyse.csv
        data5: output/data/high_risk_ever_cohort.csv
        data6: output/data/high_risk_cohort.csv
#        rds: output/data/data4analyse.rds
#prep_model_surv.r
  prep_model_surv_r:
    run: r:latest analysis/prep_model_surv.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data6: output/data/high_risk_surv_data.csv

prep_descrip_stata:
   run: stata-mp:latest analysis/data_prep_descrip.do
   needs: [gen_dataset_table]
   outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data: output/main.dta






