version: '3.0'

expectations:
  population_size: 5000

actions:

  gen_dataset_table:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/data/dataset_table.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv.gz

  prep_descrip_r:
    run: r:latest analysis/data_prep_descrip.R
    needs: [gen_dataset_table]
    outputs:
      moderately_sensitive:
        data2: output/tables/table1_redacted_8b.csv
        data3: output/tables/table1b_redacted_8b.csv
      highly_sensitive:
        data1: output/data/data4analyse.csv
        data4: output/data/high_risk_ever_cohort.csv
        data5: output/data/high_risk_cohort.csv
        rds: output/data/data4analyse.rds

  prep_descrip_stata:
   run: stata-mp:latest analysis/data_prep_descrip.do
   needs: [gen_dataset_table]
   outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data: output/main.dta






