version: '3.0'

expectations:
  population_size: 5000

actions:

  gen_dataset_table:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/data/dataset_table.csv.gz
    outputs:
      highly_sensitive:
        cohort: output/data/dataset_table.csv.gz

  prep_descrip_r:
    run: r:latest analysis/data_prep_descrip.r
    needs: [gen_dataset_table]
    outputs:
      moderately_sensitive:
        table1: output/tables/table1_sum.csv
        table2: output/tables/table1_redacted_under8.csv
      highly_sensitive:
        data1: output/data/high_risk_ever_cohort.csv
        data2: output/data/high_risk_cohort.csv

  prep_model_surv_r:
    run: r:latest analysis/prep_model_surv.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data3: output/data/high_risk_surv_data.csv

  prep_model_1surv_r:
    run: r:latest analysis/prep_model_1surv.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data4: output/data/high_risk_surv_data1.csv
  
  prep_model_2surv_r:
    run: r:latest analysis/prep_model_2surv.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data5: output/data/high_risk_surv_data2.csv

  prep_descrip_agegp_r:
    run: r:latest analysis/data_prep_descrip_1agegp.r
    needs: [prep_descrip_r]
    outputs:
      highly_sensitive:
        data6: output/data/high_risk_vars_age_rc.csv
      moderately_sensitive:
        table01: output/tables/high_risk_vars_age_rc_table.csv
      

prep_descrip_stata:
   run: stata-mp:latest analysis/data_prep_descrip.do
   needs: [gen_dataset_table]
   outputs:
      moderately_sensitive:
        log: logs/data_preparation.log
      highly_sensitive:
        data: output/main.dta






