## Import libraries
library('tidyverse')
library('here')
library('lubridate')
library('arrow')
library('dplyr')
library('readr')

## import functions
source(here("analysis", "lib", "r_funs.R"))

## Create directories 
dir_create(here::here("output", "tables"), showWarnings = FALSE, recurse = TRUE)
dir_create(here::here("output", "data"), showWarnings = FALSE, recurse = TRUE)

## Read in data 
#dataset_table.csv.gz
#C:\Users\qw\Documents\Github\prophy_effects_Sotro_Molnup\output\data
extr_data0 <- read_csv("C:/Users/qw/Documents/Github/prophy_effects_Sotro_Molnup/output/data/dataset_table.csv.gz") %>% #,
select(patient_id,age_treated,sex,age_treated_group,ethnicity_snome,ethnicity_snome_cat, had_first_covid_treat,first_covid_treat_interve,first_covid_treat_date,first_covid_treat_status,
  first_molnupiravir_date,first_sotrovimab_date,date_of_first_admis_af_treat,
  covid_first_admi_af_treat_alldiag_firstdate, apcs_admis_60daf_treat_alldiag_firstdate,ccare_covid_first_af_treat_alldiag_date,
  hosp_covid_date,  hosp_covid_classfic, hosp_covid_pdiag,  had_ccare_covid,  ccare_covid_date,  hosp_allcause_date,
  hosp_allcause_classfic,  hosp_allcause_pdiag,  hospitalise_disc_covid, hospitalise_disc_allcause,  ons_dead_date,  underly_deathcause,
  death_cause_covid,  ons_dead_tr60d_6mon_covid_treat,  ons_dead_tr60d_6mon_covid_treat2, ons_dead_trstart_60d_covid_treat,  ons_dead_trstart_30d_covid_treat) #,

 extr_data0
#extr_data <- read_csv(here::here("output", "data", "dataset_table.csv.gz")) %>%
  col_types = cols_only(                      
  patient_id = col_integer(),
  first_covid_treat_date = col_date(format = "%Y-%m-%d"),
  had_first_covid_treat = col_logical(),
  first_covid_treat_interve = col_character(),
  first_covid_treat_status = col_character(),
  date_treated = col_date(format = "%Y-%m-%d"),
  first_molnupiravir_date = col_date(format = "%Y-%m-%d"),
  first_molnupiravir_status = col_character(),
  first_molnupiravir_interve = col_character(),
  first_molnupiravir_diag = col_character(),
  first_sotrovimab_date = col_date(format = "%Y-%m-%d"),
  first_sotrovimab_status = col_character(),
  first_sotrovimab_interve = col_character(),
  first_sotrovimab_diag = col_character(),
  date_of_first_admis_af_treat = col_date(format = "%Y-%m-%d"),
  hosp_covid_date = col_date(format = "%Y-%m-%d"),
  hosp_covid_classfic = col_integer(),
  hosp_covid_pdiag = col_character(),
  had_ccare_covid = col_logical(),
  ccare_covid_date = col_date(format = "%Y-%m-%d"),
  hosp_allcause_date = col_date(format = "%Y-%m-%d"),
  hosp_allcause_classfic = col_integer(),
  hosp_allcause_pdiag = col_character(),
  hospitalise_disc_covid = col_date(format = "%Y-%m-%d"),
  hospitalise_disc_allcause = col_date(format = "%Y-%m-%d"),
  ons_dead_date = col_date(format = "%Y-%m-%d"),
  underly_deathcause = col_character(),
  death_cause_covid = col_logical(),
  ons_dead_tr60d_6mon_covid_treat = col_logical(),
  ons_dead_tr60d_6mon_covid_treat2 = col_logical(),
  ons_dead_trstart_60d_covid_treat = col_logical(),
  ons_dead_trstart_30d_covid_treat = col_logical(),
  immunosuppresant_drugs_nhsd = col_date(format = "%Y-%m-%d"),
  oral_steroid_drugs_nhsd = col_date(format = "%Y-%m-%d"),
  oral_steroid_drug_nhsd_3m_count = col_integer(),
  oral_steroid_drug_nhsd_12m_count = col_integer(),
  immunosuppresant_drugs_nhsd_ever = col_date(format = "%Y-%m-%d"),
  oral_steroid_drugs_nhsd_ever = col_date(format = "%Y-%m-%d"),
  dialysis = col_date(format = "%Y-%m-%d"),
  dialysis_icd10 = col_date(format = "%Y-%m-%d"),
  dialysis_procedure = col_date(format = "%Y-%m-%d"),
  kidney_transplant = col_date(format = "%Y-%m-%d"),
  kidney_transplant_icd10 = col_date(format = "%Y-%m-%d"),
  kidney_transplant_procedure = col_date(format = "%Y-%m-%d"),
  solid_organ_transplant_snomed = col_date(format = "%Y-%m-%d"),
  solid_organ_transplant_nhsd_snomed = col_date(format = "%Y-%m-%d"),
  solid_organ_nhsd_snomed_new = col_date(format = "%Y-%m-%d"),
  solid_organ_transplant_nhsd_opcs4 = col_date(format = "%Y-%m-%d"),
  transplant_all_y_codes_opcs4 = col_date(format = "%Y-%m-%d"),
  transplant_all_y_codes_opcs4_count = col_integer(),
  transplant_thymus_opcs4 = col_date(format = "%Y-%m-%d"),
  transplant_thymus_opcs4_count = col_integer(),
  transplant_thymus_opcs4_a = col_date(format = "%Y-%m-%d"),
  transplant_conjunctiva_y_code_opcs4 = col_logical(),
  transplant_conjunctiva_y_code_opcs4_count = col_integer(),
  transplant_conjunctiva_opcs4 = col_date(format = "%Y-%m-%d"),
  transplant_conjunctiva_opcs4_count = col_integer(),
  transplant_conjunctiva_opcs4_a = col_date(format = "%Y-%m-%d"),
  transplant_stomach_opcs4 = col_date(format = "%Y-%m-%d"),
  transplant_stomach_opcs4_count = col_integer(),
  transplant_stomach_opcs4_a = col_date(format = "%Y-%m-%d"),
  transplant_ileum_1_Y_codes_opcs4 = col_date(format = "%Y-%m-%d"),
  transplant_ileum_1_Y_codes_opcs4_count = col_integer(),
  transplant_ileum_1_opcs4 = col_date(format = "%Y-%m-%d"),
  transplant_ileum_1_opcs4_count = col_integer(),
  transplant_ileum_1_opcs4_a = col_date(format = "%Y-%m-%d"),
  transplant_ileum_2_Y_codes_opcs4 = col_date(format = "%Y-%m-%d"),
  transplant_ileum_2_Y_codes_opcs4_count = col_integer(),
  transplant_ileum_2_opcs4 = col_date(format = "%Y-%m-%d"),
  transplant_ileum_2_opcs4_count = col_integer(),
  transplant_ileum_2_opcs4_a = col_date(format = "%Y-%m-%d"),
  transplant_thymus_opcs4_2 = col_date(format = "%Y-%m-%d"),
  transplant_conjunctiva_opcs4_2 = col_date(format = "%Y-%m-%d"),
  transplant_stomach_opcs4_2 = col_date(format = "%Y-%m-%d"),
  transplant_ileum_1_opcs4_2 = col_date(format = "%Y-%m-%d"),
  transplant_ileum_2_opcs4_2 = col_date(format = "%Y-%m-%d"),
  solid_organ_transplant_nhsd = col_date(format = "%Y-%m-%d"),
  solid_organ_transplant_nhsd_new = col_date(format = "%Y-%m-%d"),
  haematopoietic_stem_cell_snomed = col_date(format = "%Y-%m-%d"),
  haematopoietic_stem_cell_icd10 = col_date(format = "%Y-%m-%d"),
  haematopoietic_stem_cell_opcs4 = col_date(format = "%Y-%m-%d"),
  haematological_malignancies_snomed = col_date(format = "%Y-%m-%d"),
  haematological_malignancies_icd10 = col_date(format = "%Y-%m-%d"),
  sickle_cell_disease_nhsd_snomed = col_date(format = "%Y-%m-%d"),
  sickle_cell_disease_nhsd_icd10 = col_date(format = "%Y-%m-%d"),
  haematopoietic_stem_cell_snomed_ever = col_date(format = "%Y-%m-%d"),
  haematopoietic_stem_cell_icd10_ever = col_date(format = "%Y-%m-%d"),
  haematopoietic_stem_cell_opcs4_ever = col_date(format = "%Y-%m-%d"),
  haematological_malignancies_snomed_ever = col_date(format = "%Y-%m-%d"),
  haematological_malignancies_icd10_ever = col_date(format = "%Y-%m-%d"),
  haematological_disease_nhsd_ever = col_date(format = "%Y-%m-%d"),
  immunosupression_nhsd = col_date(format = "%Y-%m-%d"),
  immunosupression_nhsd_new = col_date(format = "%Y-%m-%d"),
  cancer_opensafely_snomed = col_date(format = "%Y-%m-%d"),
  cancer_opensafely_snomed_new = col_date(format = "%Y-%m-%d"),
  cancer_opensafely_snomed_ever = col_date(format = "%Y-%m-%d"),
  high_risk_covid_thera_MOL_count = col_integer(),
  high_risk_covid_thera_MOL_count_dist = col_integer(),
  high_risk_covid_thera_SOT02_count_dist = col_integer(),
  high_risk_covid_thera_CASIM05_count_dist = col_integer(),
  preg_36wks_date = col_date(format = "%Y-%m-%d"),
  is_pregdel = col_logical(),
  pregnancy = col_character(),
  covid_first_admi_af_treat_alldiag_firstdate = col_date(format = "%Y-%m-%d"),
  apcs_admis_60daf_treat_alldiag_firstdate = col_date(format = "%Y-%m-%d"),
  ccare_covid_first_af_treat_alldiag_date = col_date(format = "%Y-%m-%d"),
##DEMOGRAPHIC
  dob = col_date(format = "%Y-%m-%d"),
  dod = col_date(format = "%Y-%m-%d"),
  sex = col_character(),
  age_sstart = col_integer(),
  age_sstart_group = col_character(),
  age_treated = col_integer(),
  age_treated_group = col_character(),
  ethnicity_snome = col_integer(),
  ethnicity_snome_cat = col_character(),
  ethnicity_ctv3 = col_integer(),
  care_home_primis = col_logical(),
  imd = col_character(),
  imd1 = col_integer(),
  region = col_character(),
  stp = col_character(),
  dereg_date = col_logical(),
  dereg_date1 = col_logical(),
  rural_urban = col_integer(),
  bmi = col_integer(),
  bmi_date = col_date(format = "%Y-%m-%d"),
  total_covid_vacc = col_integer(),
  covid_vacc01 = col_date(format = "%Y-%m-%d"),
  covid_vacc02 = col_date(format = "%Y-%m-%d"), 
  covid_vacc03 = col_date(format = "%Y-%m-%d"), 
  covid_vacc04 = col_logical(),
  covid_vacc_last = col_date(format = "%Y-%m-%d"),                             
  last_vaccination_date = col_date(format = "%Y-%m-%d"),                 
   
  ),
)

# write.csv(both, here::here("output", "tables", "cohort_data4analyse.csv"),
#           row.names = FALSE)

# Process data ----
cat("#### process data ####\n")

dim(extr_data)
str(extr_data,list.len= ncol(extr_data),give.attr = F)

sel_data<- extr_data %>% slecet()
# ## Clean data
# data_processed_clean <- data_processed_combined %>%
#   filter(elig_start <= Sys.Date(),
#          !(patient_id %in% unique(dup_ids$patient_id)),
#          !(patient_id %in% unique(date_ids$patient_id))) %>%
#   select(
    
#     # ID
#     patient_id, eligibility_status,
    
#     # Censoring
#     start_date, has_died, death_date, dereg_date, registered_eligible, registered_treated,
       
#     # Outcomes
#     covid_positive_test_30_days_post_elig_or_treat, covid_positive_test_30_days_post_elig_or_treat_date,
#     covid_hospital_admission, covid_hospitalisation_outcome_date,
#     covid_hospitalisation_critical_care,
#     covid_death, any_death)

# cat("#### patients excluded ####\n")
# print(dim(data_processed_combined)[1] - dim(data_processed_clean)[1])

# rm(data_processed_combined)


# cat("#### treated patients symptomatic test ####\n")
# print(table(subset(data_processed_clean, !is.na(treatment_date))$symptomatic_covid_test))

# Save dataset(s) ----
write_rds(sel_data, here::here("output", "data", "sel_data.rds"), compress = "gz")

#####
(patient_id,had_first_covid_treat,first_covid_treat_date,first_covid_treat_interve)
spc_tbl_ [166 × 133] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ patient_id                                 : num [1:166] 48646 21004 12304 44561 21522 ...
 $ first_covid_treat_date                     : Date[1:166], format: "2022-02-02" "2022-01-06" "2022-01-15" "2021-12-27" ...
 $ had_first_covid_treat                      : logi [1:166] TRUE TRUE TRUE TRUE TRUE TRUE ...
 $ first_covid_treat_interve                  : chr [1:166] "Sotrovimab" "Molnupiravir" "Molnupiravir" "Sotrovimab" ...
 $ first_covid_treat_status                   : chr [1:166] "Approved" "Approved" "Approved" "Treatment Complete" ...
 $ date_treated                               : Date[1:166], format: "2022-02-02" "2022-01-06" "2022-01-15" "2021-12-27" ...
 $ first_molnupiravir_date                    : Date[1:166], format: NA "2022-01-06" "2022-01-15" NA ...
 $ first_molnupiravir_status                  : chr [1:166] NA "Approved" "Approved" NA ...
 $ first_molnupiravir_interve                 : chr [1:166] NA "Molnupiravir" "Molnupiravir" NA ...
 $ first_molnupiravir_diag                    : chr [1:166] NA "4Dw76ithB_vl4L" "z" NA ...
 $ first_sotrovimab_date                      : Date[1:166], format: "2022-02-02" NA NA "2021-12-27" ...
 $ first_sotrovimab_status                    : chr [1:166] "Approved" NA NA "Treatment Complete" ...
 $ first_sotrovimab_interve                   : chr [1:166] "Sotrovimab" NA NA "Sotrovimab" ...
 $ first_sotrovimab_diag                      : chr [1:166] "Vy-Lk_7M8GUTr" NA NA "HnUlH" ...
 $ date_of_first_admis_af_treat               : Date[1:166], format: "2022-04-21" "2022-07-02" "2023-02-03" "2022-09-21" ...
 $ hosp_covid_date                            : Date[1:166], format: NA NA NA NA ...
 $ hosp_covid_classfic                        : num [1:166] NA NA NA NA NA NA NA NA NA NA ...
 $ hosp_covid_pdiag                           : chr [1:166] NA NA NA NA ...
 $ had_ccare_covid                            : logi [1:166] NA NA NA NA NA NA ...
 $ ccare_covid_date                           : Date[1:166], format: NA NA NA NA ...
 $ hosp_allcause_date                         : Date[1:166], format: "2022-04-21" NA NA NA ...
 $ hosp_allcause_classfic                     : num [1:166] 1 NA NA NA 1 NA 1 NA NA NA ...
 $ hosp_allcause_pdiag                        : chr [1:166] "Z992" NA NA NA ...
 $ hospitalise_disc_covid                     : Date[1:166], format: NA NA NA NA ...
 $ hospitalise_disc_allcause                  : Date[1:166], format: NA NA NA NA ...
 $ ons_dead_date                              : Date[1:166], format: "2023-01-04" "2023-09-07" "2024-04-15" "2021-08-19" ...
 $ underly_deathcause                         : chr [1:166] NA "U072" "U099" "U099" ...
 $ death_cause_covid                          : logi [1:166] TRUE TRUE TRUE TRUE NA NA ...
 $ ons_dead_tr60d_6mon_covid_treat            : logi [1:166] FALSE FALSE FALSE FALSE NA NA ...
 $ ons_dead_tr60d_6mon_covid_treat2           : logi [1:166] FALSE FALSE FALSE FALSE NA NA ...
 $ ons_dead_trstart_60d_covid_treat           : logi [1:166] FALSE FALSE FALSE FALSE NA NA ...
 $ ons_dead_trstart_30d_covid_treat           : logi [1:166] FALSE FALSE FALSE FALSE NA NA ...
 $ immunosuppresant_drugs_nhsd                : Date[1:166], format: "2022-01-01" NA "2021-11-14" NA ...
 $ oral_steroid_drugs_nhsd                    : Date[1:166], format: NA NA NA NA ...
 $ oral_steroid_drug_nhsd_3m_count            : num [1:166] 0 0 0 0 0 0 0 0 0 0 ...
 $ oral_steroid_drug_nhsd_12m_count           : num [1:166] 0 0 0 0 0 0 0 0 0 0 ...
 $ immunosuppresant_drugs_nhsd_ever           : Date[1:166], format: "2022-01-01" NA "2021-11-14" NA ...
 $ oral_steroid_drugs_nhsd_ever               : Date[1:166], format: NA NA NA NA ...
 $ dialysis                                   : Date[1:166], format: NA "2020-11-29" NA "2020-01-11" ...
 $ dialysis_icd10                             : Date[1:166], format: NA NA NA NA ...
 $ dialysis_procedure                         : Date[1:166], format: "2020-07-17" NA NA NA ...
 $ kidney_transplant                          : Date[1:166], format: NA "2021-11-24" NA NA ...
 $ kidney_transplant_icd10                    : Date[1:166], format: NA NA NA NA ...
 $ kidney_transplant_procedure                : Date[1:166], format: NA NA NA NA ...
 $ solid_organ_transplant_snomed              : Date[1:166], format: NA NA NA NA ...
 $ solid_organ_transplant_nhsd_snomed         : Date[1:166], format: NA NA NA NA ...
 $ solid_organ_nhsd_snomed_new                : Date[1:166], format: NA NA NA NA ...
 $ solid_organ_transplant_nhsd_opcs4          : Date[1:166], format: NA NA NA NA ...
 $ transplant_all_y_codes_opcs4               : Date[1:166], format: NA "2021-12-12" NA NA ...
 $ transplant_all_y_codes_opcs4_count         : num [1:166] 0 2 0 0 0 0 0 0 0 0 ...
 $ transplant_thymus_opcs4                    : Date[1:166], format: NA NA NA NA ...
 $ transplant_thymus_opcs4_count              : num [1:166] 0 0 0 0 0 0 0 0 0 0 ...
 $ transplant_thymus_opcs4_a                  : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_conjunctiva_y_code_opcs4        : Date[1:166], format: NA NA NA NA ...
 $ transplant_conjunctiva_y_code_opcs4_count  : num [1:166] 0 0 0 0 0 0 0 0 0 0 ...
 $ transplant_conjunctiva_opcs4               : Date[1:166], format: NA NA NA NA ...
 $ transplant_conjunctiva_opcs4_count         : num [1:166] 0 0 0 0 0 0 0 0 0 0 ...
 $ transplant_conjunctiva_opcs4_a             : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_stomach_opcs4                   : Date[1:166], format: NA NA "2021-06-04" NA ...
 $ transplant_stomach_opcs4_count             : num [1:166] 0 0 1 0 0 0 0 0 0 0 ...
 $ transplant_stomach_opcs4_a                 : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_ileum_1_Y_codes_opcs4           : Date[1:166], format: NA "2021-12-12" NA NA ...
 $ transplant_ileum_1_Y_codes_opcs4_count     : num [1:166] 0 1 0 0 0 0 0 0 0 0 ...
 $ transplant_ileum_1_opcs4                   : Date[1:166], format: NA NA NA NA ...
 $ transplant_ileum_1_opcs4_count             : num [1:166] 0 0 0 0 0 0 0 0 0 0 ...
 $ transplant_ileum_1_opcs4_a                 : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_ileum_2_Y_codes_opcs4           : Date[1:166], format: NA "2021-10-24" NA NA ...
 $ transplant_ileum_2_Y_codes_opcs4_count     : num [1:166] 0 1 0 0 0 0 0 0 0 0 ...
 $ transplant_ileum_2_opcs4                   : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_ileum_2_opcs4_count             : num [1:166] 0 0 0 0 0 0 0 0 0 0 ...
 $ transplant_ileum_2_opcs4_a                 : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_thymus_opcs4_2                  : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_conjunctiva_opcs4_2             : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_stomach_opcs4_2                 : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_ileum_1_opcs4_2                 : logi [1:166] NA NA NA NA NA NA ...
 $ transplant_ileum_2_opcs4_2                 : logi [1:166] NA NA NA NA NA NA ...
 $ solid_organ_transplant_nhsd                : Date[1:166], format: NA NA NA NA ...
 $ solid_organ_transplant_nhsd_new            : Date[1:166], format: NA NA NA NA ...
 $ haematopoietic_stem_cell_snomed            : Date[1:166], format: NA NA NA NA ...
 $ haematopoietic_stem_cell_icd10             : Date[1:166], format: NA NA NA NA ...
 $ haematopoietic_stem_cell_opcs4             : Date[1:166], format: NA NA NA NA ...
 $ haematological_malignancies_snomed         : Date[1:166], format: NA NA NA NA ...
 $ haematological_malignancies_icd10          : Date[1:166], format: "2020-07-17" "2021-10-24" "2021-06-04" NA ...
 $ sickle_cell_disease_nhsd_snomed            : Date[1:166], format: NA NA NA NA ...
 $ sickle_cell_disease_nhsd_icd10             : Date[1:166], format: NA NA NA NA ...
 $ haematopoietic_stem_cell_snomed_ever       : Date[1:166], format: NA NA NA NA ...
 $ haematopoietic_stem_cell_icd10_ever        : Date[1:166], format: NA NA NA NA ...
 $ haematopoietic_stem_cell_opcs4_ever        : Date[1:166], format: NA NA NA NA ...
 $ haematological_malignancies_snomed_ever    : Date[1:166], format: NA NA NA NA ...
 $ haematological_malignancies_icd10_ever     : Date[1:166], format: "2020-07-17" "2021-10-24" "2021-06-04" NA ...
 $ haematological_disease_nhsd_ever           : Date[1:166], format: "2020-07-17" "2021-10-24" "2021-06-04" NA ...
 $ immunosupression_nhsd                      : Date[1:166], format: NA NA NA NA ...
 $ immunosupression_nhsd_new                  : Date[1:166], format: NA NA NA NA ...
 $ cancer_opensafely_snomed                   : Date[1:166], format: NA NA "2021-09-24" NA ...
 $ cancer_opensafely_snomed_new               : Date[1:166], format: NA NA "2021-09-24" NA ...
 $ cancer_opensafely_snomed_ever              : Date[1:166], format: NA "2020-11-29" "2021-09-24" "2020-01-11" ...
 $ high_risk_covid_thera_MOL_count            : num [1:166] 1 1 4 4 5 2 1 2 2 2 ...
 $ high_risk_covid_thera_MOL_count_dist       : num [1:166] 1 1 1 1 1 1 1 1 1 1 ...
 $ high_risk_covid_thera_SOT02_count_dist     : num [1:166] 1 1 1 1 1 1 1 1 1 1 ...
 $ high_risk_covid_thera_CASIM05_count_dist   : num [1:166] 1 1 1 1 1 1 1 1 1 1 ...
 $ preg_36wks_date                            : Date[1:166], format: NA NA NA NA ...
 $ is_pregdel                                 : logi [1:166] FALSE FALSE FALSE FALSE FALSE FALSE ...
 $ pregnancy                                  : chr [1:166] "Not preg" "Not preg" "Not preg" "Not preg" ...
 $ covid_first_admi_af_treat_alldiag_firstdate: Date[1:166], format: "2022-04-21" "2023-11-02" "2023-02-03" "2024-03-08" ...
 $ apcs_admis_60daf_treat_alldiag_firstdate   : Date[1:166], format: "2022-04-21" NA NA NA ...
 $ ccare_covid_first_af_treat_alldiag_date    : Date[1:166], format: "2022-04-21" "2023-11-02" "2023-02-03" NA ...
 $ dob                                        : Date[1:166], format: "1996-03-01" "1986-02-01" "1963-03-01" "1965-03-01" ...
 $ dod                                        : Date[1:166], format: NA NA NA NA ...
 $ sex                                        : chr [1:166] "female" "female" "female" "female" ...
 $ age_sstart                                 : num [1:166] 25 35 58 56 43 34 49 21 32 47 ...
 $ age_sstart_group                           : chr [1:166] "18-29" "30-39" "50-59" "50-59" ...
 $ age_treated                                : num [1:166] 25 35 58 56 43 34 49 21 32 47 ...
 $ age_treated_group                          : chr [1:166] "18-29" "30-39" "50-59" "50-59" ...
 $ ethnicity_snome                            : num [1:166] NA NA NA NA NA NA NA NA NA NA ...
 $ ethnicity_snome_cat                        : chr [1:166] "Unknown" "Unknown" "Unknown" "Unknown" ...
 $ ethnicity_ctv3                             : num [1:166] 3 5 5 1 1 5 4 1 4 1 ...
 $ care_home_primis                           : logi [1:166] TRUE FALSE FALSE TRUE FALSE FALSE ...
 $ imd                                        : chr [1:166] "2" "unknown" "unknown" "3" ...
 $ imd1                                       : num [1:166] 13100 NA NA 15200 NA 14800 20800 NA NA 10800 ...
 $ region                                     : chr [1:166] "East Midlands" "North West" "Yorkshire and The Humber" "South East" ...
 $ stp                                        : chr [1:166] "E54000088" "E54000061" "E54000058" "E54000075" ...
 $ dereg_date                                 : logi [1:166] NA NA NA NA NA NA ...
 $ dereg_date1                                : logi [1:166] NA NA NA NA NA NA ...
 $ rural_urban                                : num [1:166] 7 NA NA 8 NA 2 4 NA NA 7 ...
 $ bmi                                        : logi [1:166] NA NA NA NA NA NA ...
 $ bmi_date                                   : logi [1:166] NA NA NA NA NA NA ...
 $ total_covid_vacc                           : num [1:166] 1 0 0 0 0 0 1 2 0 0 ...
 $ covid_vacc01                               : Date[1:166], format: "2021-11-01" NA NA NA ...
 $ covid_vacc02                               : Date[1:166], format: NA NA NA NA ...
 $ covid_vacc03                               : Date[1:166], format: NA NA NA NA ...
 $ covid_vacc04                               : Date[1:166], format: NA NA NA NA ...
 $ covid_vacc_last                            : Date[1:166], format: "2021-11-01" NA NA NA ...
 $ last_vaccination_date                      : Date[1:166], format: "2021-11-01" NA NA NA ...
